require('dotenv/config');

const {
  USER_CNPJ,
  USER_PASS,
  USER_SERVICE_CODE,
  COMPANY_CNPJ,
  COMPANY_NAME,
  COMPANY_ZIP_CODE,
  COMPANY_DISTRICT,
  COMPANY_CITY,
  COMPANY_STREET,
  COMPANY_EMAIL,
  COMPANY_STATE,
  NOTE_CODE,
  NOTE_QUANTITY,
  NOTE_VALUE,
} = process.env;

module.exports = {
  USER_CNPJ,
  USER_PASS,
  USER_SERVICE_CODE,
  COMPANY_CNPJ,
  COMPANY_NAME,
  COMPANY_ZIP_CODE,
  COMPANY_DISTRICT,
  COMPANY_CITY,
  COMPANY_STREET,
  COMPANY_EMAIL,
  COMPANY_STATE,
  NOTE_CODE,
  NOTE_QUANTITY,
  NOTE_VALUE,
};
